version: "3"
services:
  app:
    image: tehwey/paste-my-taste:latest
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=prod
      - API_KEY=
      - STORAGE_BACKEND=persistent
      - STORAGE_PATH=/pmt-data
    volumes:
     - /home/dewey/services/pmt/pmt-data:/pmt-data
